services:
  - type: web
    name: arceus-xd-mini
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BOT_NAME
        value: ARCEUS XD MINI
      - key: PREFIX
        value: .
      - key: OWNER_NUMBER
        sync: 917602624961
      - key: OWNER_NAME
        value: Crimex X
      - key: PAIRING_NUMBER
        sync: 917602624961
